# Generated by Django 6.0.2 on 2026-03-03 16:18

from django.db import migrations

def backfill_root_job(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")

    jobs = list(Job.objects.all())
    job_map = {job.id: job for job in jobs}

    # children 매핑 생성
    children_map = {}
    for job in jobs:
        if job.previous_job_id:
            children_map.setdefault(job.previous_job_id, []).append(job)

    # root 찾기
    roots = [job for job in jobs if job.previous_job_id is None]

    for root in roots:
        root.root_job_id = root.id

        stack = [root]
        while stack:
            parent = stack.pop()
            children = children_map.get(parent.id, [])

            for child in children:
                child.root_job_id = root.id
                stack.append(child)

    Job.objects.bulk_update(jobs, ["root_job"])

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_root_job'),
    ]

    operations = [
        migrations.RunPython(backfill_root_job),
    ]
