# Generated by Django 6.0.2 on 2026-03-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_root_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='root_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='jobs.job'),
        ),
    ]
