# Generated by Django 6.0.2 on 2026-03-03 17:25

from django.db import migrations

def backfill_root_job(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    roots = Job.objects.filter(previous_job__isnull=True)
    
    for root in roots:
        root.root_job = root
        root.save()
        stack = [root]
        while stack:
            parent = stack.pop()
            children = Job.objects.filter(previous_job=parent)
            for child in children:
                child.root_job = root
                child.save()
                stack.append(child)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_root_job'),
    ]

    operations = [
        migrations.RunPython(backfill_root_job),
    ]
