# Generated by Django 6.0.2 on 2026-03-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20260304_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='root_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='jobs.job'),
        ),
    ]
