# Generated by Django 5.2.13 on 2026-05-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_root_job'),
        ('servers', '0004_alter_server_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='servers.server'),
        ),
    ]
