# Generated by Django 6.0.2 on 2026-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(choices=[('online', '운영 중'), ('standby', '대기 중'), ('provisioning', '구성 중'), ('maintenance', '유지보수 중'), ('rebooting', '재부팅 중'), ('down', '서비스 중단'), ('unreachable', '통신 불가'), ('offline', '전원 꺼짐'), ('decommissioned', '폐기됨')], default='online', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
