# Generated by Django 6.0.2 on 2026-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('status', models.CharField(choices=[('online', '운영 중'), ('standby', '대기 중'), ('provisioning', '설치/배포 중'), ('maintenance', '점검 중'), ('rebooting', '재부팅 중'), ('down', '다운/장애'), ('unreachable', '응답 없음'), ('offline', '종료'), ('decommissioned', '폐기')], default='online', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
