# Generated by Django 5.2.13 on 2026-05-02 15:08

from django.db import migrations

def infer_environment(name: str) -> str:
    """서버 이름에서 environment 추론
    """
    n = name.lower()
    if any(k in n for k in ("prod", "-p-", "production")):
        return "prod"
    if any(k in n for k in ("stg", "stage", "staging")):
        return "stg"
    if any(k in n for k in ("dev", "development", "local")):
        return "dev"
    # 기본 정책: 불분명한 건 prod로 처리
    return "prod"


def backfill(apps, schema_editor):
    Server = apps.get_model("servers", "Server")
    for srv in Server.objects.filter(environment__isnull=True):
        srv.environment = infer_environment(srv.name)
        srv.save(update_fields=["environment"])


def reverse(apps, schema_editor):
    Server = apps.get_model("servers", "Server")
    Server.objects.update(environment=None)

class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_environment'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse),
    ]
