# Generated by Django 5.2.13 on 2026-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_backfill_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='environment',
            field=models.CharField(choices=[('prod', '운영 환경'), ('stg', '스테이징 환경'), ('dev', '개발 환경')], db_index=True, default='dev', max_length=10),
            preserve_default=False,
        ),
    ]
