---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: db
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAdZQ5uQkzX+y7EljRktf0Lv52Cm1Qyde1SZST6MiRHBmHEVt1pypXsRIC08vARBDGEdEZN9M3Nj+JuG8PpiNy4DI5uLqLY1fG1f9JbQlaZ5Vb8eP37EDNhexqbD5FceDHsrfKzG9dBEBa/bgDmTqN+ydbM1GDsjvBxRSMSIaElLM8xwk1OS67h62zT3y/0PlchPSx1sexK/EZ9/fF8U2RBkHtRwm7M8QBIH+ufhVo3j8MMY3dd4znVYBe+gXVAITVXVJCLttFRqHlM92bttjNvMa61osMkg7JFe6fMFmE0WJxKPhUjRvyvVKJFuavDH5CkWO725r7LvEtpose33iiNl7WqP4sXEGCNGup1I/2fyzUqz6u7FIk2dwxpVR0VaIqlLPF98kIAg+hI3prHdCU2ERcFk0FmJ+3tliGYAEn+U2XYT3OU3xahdtWNHVKJ/OEleXYUKxdZsjEBHh6LbC+IADV352A9cs5kUQeMMqQhHuHxodI4j7g2r8KoWm8waYR4V6eWJmEiqgmDaZ/4yKsJVymhPfzWJAfXnqvC7rl2k8xS/964j1TbcY+c2+OKcExjA8mLEqBhC5+WCQDcJO0JefJGH8XKYIbSHkYZBwIYaiWWpp1j5Od/L5h/NEEBIfdWB6xgNG55WPElcBvqI99TGFVjjepDAFL58YjG+C9rrj7SKI0dydjmKgTlOIUhFe9kkGA2H2TeOA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-secret
      namespace: db
    type: Opaque
