---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: server-job-manager-secret
  namespace: app
spec:
  encryptedData:
    DB_PASSWORD: AgCWD/C1Cc9EVX4u2hgbs/Tf+sVRbMbLmiuUv4GX7VKFFrCkdA1FsQMz2xPlAYvJ8l1ZcnhP6aAyhWnooOwp/dseF2rL9xRzvq5FFSbTjRUre+u+1N54PHBs/UomT3yQ/YS5MLyb07U/wQZXCFAgqwMVIkzJZzMpvzDbRDWP11eda2YcKFEYD7vOwmIMwgr8VXMJkwc/cIcjRIaBgQeHOAtOPSsqeZIm2ASFp8D5mYaiYU2jIDvFQlay4ghGsqARMQUowntWkBF+1tI1XubEUEROihI2oedbHb9ibltJW3C49+ghsPhgY96iBPCKOUxMOJ3pGg7CF2KMno6JmjYVx8ZY5Kw/ZClM6GecVi/lqdjOkch87PjFqB1b71oR1UVQbgJROsbG7n3VKbBMdgetaYxAu+K7lQlEsvcE/90h6z8hqKbgCU5MdWj/57FQKxomDDYzDgzPRW8AT8zbkgWz1pljJ3hNcumKG31nuF+nOWaHJfrA5qrvqv3OfdB1pmw5TCBnQEl2YnQS01mWPRznVJtM5oWX+m2++SIfwgxHtH6mQ/6xpgtLVkQXr8k2/DC3QGETTmlF1YQPfCo7zbAUxe8qJwY+qHLONWMmQLhnxinKxoxZe2dCv4Lhsi0Qenk0lGTRHcVfULyAO870CrLoeL9eX0+qx8QalnPLIScUAney66vyZtpJhWs+Qc5n71Cpeh7N3HrQbqJKJw==
    DJANGO_SECRET_KEY: AgB8uhBLnOZ0JKNK7KnxcE1sZBPKcDzLPDMq3uwlxg1aNVPu4Z0wLUoDDyKg1lc6+GuscjCwdEJatT9sFLrDSkqtXDeqSMW3IshwV4njmzKh4USao6XVUBsPJnaEZctzfLY9MtpWByYBZGBqCHW2QatymRfBKbyNBYci7k/+ftMO6FKlR5VM9KG5SHWYQSuAlmMcYIeex3Vmg2l/3ZTBAYeRSY30Z/RZCm5aI7TrO8OlFxyFJEfAK6SAVBtk1D0CS6uzTEze76tX5EYrx1obA8mjTGYepzCIPn0Cvutk6E8nQ5YzUSpkLetGYF7+8woJeP4y+MThEVS5Xm6eb0kiSDiHGAM+EErajLqw31BR367fXwX/nL7j2pxjQH9L9SUMeegjH4bZxTEn+RcdmeJXNTuw48/FKYFTkg+PNePO0gtVL9zSXoukc8osB8yp67sBaOXP+9I0GaJDXMi1ntV1PxU7LHOEjyw6nQDDhcyqg++bbpHDmc8ybk/xo+N9X3kIMV9Q40ugmExn63ptQNMRO0GThclPDSmOEmDbr2yV+cqHDeGB4jTvytj9u4aK9ZPZaizYiHtZ0deJ92TSJEmXpeqimaXqGnDWmnFcvucx5tpP66yUUIu0JsDyigSHt9ZqNygYOXMziBhXqh6xhHdbEbVUjGLJ1fyWHZaMYoPAUgXK/FwO3b7GPEAa78aAg9SAYvj5IC2hUyGHRK9i5AUGY0YtAML6TZ+PbqS33Bg4c7SFnbp2Sf8bCRFTV/SgIV2M0Axgfz4qBV0BODwywvza8UxUci3LVTc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: server-job-manager-secret
      namespace: app
    type: Opaque
